language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- yarn install
script: 
- yarn test:check
after_script: cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
env:
  global:
    secure: a43WYB1N/32zzxa9LZT0yt4MI7X8JsQJOjGiL0n8ciEs+lplPCZck4UAYnpGf40pLAhzlx0KzejdCLMa05S6zcy1d3OMrxCjAz7je3PlyRO0nSKLvzLU3EhoKKLusyAX3dAoJwpv4vZQ5jvG+KL0p0Lle6b+K1hhF6c013fYRLVSMnFCt42ZY1ol4WWRmMDOzTXUk/6R1kPBKBDcgSTKkUl5+aQ+8aAxeJJ8VnSfsfzSdozsuAaIdJgHTh9xi6mwTkiGc9BCYbZe+ONDhbTg4d5iAO8y4U3s2cWQnN40HDfijZhZIb0NZ8ltvyBBZA69bDfAys362wvqqdpv/60cwqVvoX0zxBcg7DK8W99VKkAb7zarLxoaqhZObrmEXc4CGImiQZ+g59tuXG3lWpe/RQ3h6hDhq6zUj/54kEB8LjRUJLwK6b0GkBsS19zsZafbCcRP0zpS9bA1QzSalrMzeu2//WGFJpXkBQcv18nuydPtAITF/JhZIY9YXc2iEn0JPLq6cT8l9VeESsMfR+6Nan9nqPnNZFtXbH6+cED5lvbEm30n9mnZYPzpZzX+SEG532QvLSXu2fvQdbqpg486TxDZixNMhNkjiY4c0uFKV0jikbD9S1ho9JHHcU9VqwIysNHVXfdZ/sxnBBu0blCgFVfMc1XNVfDMptVgDOcNq88=
