name: js-sdsl CI

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'yarn'
    - name: install
      run: yarn install
    - name: test
      run: yarn test:check
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() && contains(github.event.head_commit.message, 'publish@') }}
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'yarn'
    - name: install
      run: yarn install
    - name: build
      run: yarn build
    - name: publish
      run: yarn publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  release:
    needs: publish
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() && contains(github.event.head_commit.message, 'publish@') }}
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version
    - name: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.version }}
        release_name: v${{ steps.package-version.outputs.version }}
        prerelease: false
  deploy:
    needs: publish
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() && contains(github.event.head_commit.message, 'publish@') }}
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'yarn'
    - name: install
      run: yarn install
    - name: generate type documentation
      run: yarn generate
    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
