name: js-sdsl test CI

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'yarn'
    - name: install
      run: yarn install
    - name: test
      run: yarn test:check
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
