name: lint-code

on: ['push', 'pull_request']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
      - name: Lint commit
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
